#!/bin/bash
set -e

#    Copyright (C) 2010  Daniel Richman
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    For a full copy of the GNU General Public License,
#    see <http://www.gnu.org/licenses/>.

echo "Temporary Directory files/download"
if [ ! -d files/download ]; then
	mkdir -v files/download
fi


if [ -d files/download/temp ]; then
	echo "Removing files/download/temp"
	rm -Rf files/download/temp
fi

if [ ! -f files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso ] || [ "$ISOUPDATE" == "update" ]; then
	echo "Downloading mini.iso for $LINUXDISTRO $DISTROVERSION arch $LINUXARCH"
	case $LINUXDISTRO in 
		"debian")
			wget -O files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso http://ftp.debian.org/debian/dists/$DISTROVERSION/main/installer-$LINUXARCH/current/images/netboot/mini.iso
			wget  -O files/download/MD5SUMS http://ftp.debian.org/debian/dists/$DISTROVERSION/main/installer-$LINUXARCH/current/images/MD5SUMS
                        SUM=`cat files/download/MD5SUMS | grep /netboot/mini.iso | sed 's/  .\/netboot.*$//'`
                        if [ "`md5sum files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso | cut -f1 -d' '`" == "$SUM" ]; then
                                echo Verified md5sum $SUM
                                rm files/download/MD5SUMS
                        else
                                echo Incorrect md5sum
				rm files/download/MD5SUMS
                                exit 1
                        fi
		;;
		"ubuntu")
			wget -O files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso http://archive.ubuntu.com/ubuntu/dists/$DISTROVERSION/main/installer-$LINUXARCH/current/images/netboot/mini.iso
			wget -O files/download/SHA1SUMS http://archive.ubuntu.com/ubuntu/dists/$DISTROVERSION/main/installer-$LINUXARCH/current/images/SHA1SUMS
			SUM=`cat files/download/SHA1SUMS | grep /netboot/mini.iso | sed 's/  .\/netboot.*$//'`
			if [ "`sha1sum files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso | cut -f1 -d' '`" == "$SUM" ]; then
			        echo Verified sha1sum $SUM
				rm files/download/SHA1SUMS
			else
				echo Incorrect sha1sum
				rm files/download/SHA1SUMS
				exit 1
			fi
		;;
		*)
			echo "Unknow dritrib !"
		;;
	esac
fi

echo Loop-mounting files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso on files/download/temp
echo sudo mount -o loop files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso files/download/temp
mkdir -v files/download/temp
sudo mount -o loop files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso files/download/temp

mkdir -p files/orig

echo Copying isolinux.bin, initrd.gz and linux to ./files/orig
cp -v files/download/temp/{isolinux.bin,initrd.gz,linux} files/orig/
chmod u+w files/orig/{isolinux.bin,initrd.gz,linux}

echo Unmounting files/download/mini-$LINUXDISTRO-$DISTROVERSION-$LINUXARCH.iso
echo sudo umount files/download/temp
sudo umount files/download/temp
